---
- name: check if system reboot is required
  hosts: all
  become: yes
  tasks:
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: send discord message when reboot is required
      uri:
        url: "https://discord.com/api/webhooks/1172625816639778877/pKPki8EM0dVGR0MZ9QtadwD2K8UEnb9lOazqdMJD_RyAdVYbW4lL4z9PNrcGSaQ2S5dh"
        method: POST
        body_format: json
        body: '{"content": "Reboot is required on ``{{ inventory_hostname }}``!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists
